name: effect-size-and-significance-bubble
type: "column"
description: |
  This spell allows to create a bubble plot for (biological) effect sizes that are associated with a significance p-value.
example:
  code: |
    render-table:
      columns:
        effect size with diverging color scheme:
          spell:
            url: <url>
            with:
              effect_size: "effect size with diverging color scheme"
              effect_size_domain_min: -2
              effect_size_domain_mid: 0
              effect_size_domain_max: 2
              effect_size_color_scheme: viridis
              effect_significance: "p-value for binned bubble size"
  test-data: tests/data1.csv
authors:
  - Felix Wiegand
  - David Lähnemann
