name: p-value
type: "column"
description: |
  This spell generates a heatmap visualization to represent the distribution of p-values or statistical significance in data.
  The heatmap uses a linear color scale to map values to a gradient from green over white to organge.
  The significance_threshold (e.g., p = 0.05) - a boundary between statistical significance and non-significance - can be adjusted dynamically based on the context or dataset.
example:
  code: |
    render-table:
      columns:
        some p-value column:
          spell:
            url: <url>
            with:
              significance_threshold: 0.05
  test-data: tests/data.tsv
authors:
  - Johannes Köster
  - Felix Wiegand
