name: multi-bubbles
type: "column"
description: |
  This spell allows to create a bubble plot while using different columns for the bubbles sizes and colors
example:
  code: |
    render-table:
      columns:
        column used for size:
          spell:
            url: <url>
            with:
              color: "column used for color"
              color_domain_min: 0
              color_domain_max: 100
              color_scale: linear
              size: "column used for size"
              size_domain_min: 0
              size_domain_max: 100
              size_scale: linear
              color_scheme: viridis
  test-data: tests/data1.csv
authors:
  - Felix Wiegand
