name: testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.2-2' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: environment.yaml
          cache-environment: false # we always want the latest stable datavzrd
          post-cleanup: 'all'
      - name: Run tests
        shell: bash -el {0}
        run: |
          pytest -v