name: testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.2-2' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: environment.yaml
          cache-environment: false # we always want the latest stable datavzrd
          post-cleanup: 'all'
      - name: Run tests
        shell: bash -el {0}
        run: |
          pytest -v
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test outputs
          path: test_outputs/